version: "3.2"

networks:
  partnermanagement_net:

services:
  
  partnermanagement-postgres:
    image: postgres:9.6.14
    container_name: partnermanagement-postgres
    restart: always
    networks:
      - ${partnermanagement_net:-partnermanagement_net}
    ports:
      - "9001:5432"
    environment:
      - POSTGRES_PASSWORD=partnermanagement
      - POSTGRES_USERNAME=partnermanagement
      - POSTGRES_MULTIPLE_DATABASES=partnermanagement
    volumes:
      - partnermanagement-pgsql:/var/lib/partnermanagement-pgsql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  partnermanagement-service:
    image: ${DOCKER_IMAGE_REGISTRY_IP:-10.113.56.67}/ngp-${PROJECT:-develop}/partnermanagement-service:${TAG}
    container_name: partnermanagement-service
    restart: always
    networks:
      - ${partnermanagement_net:-partnermanagement_net}
    environment:
      JAVA_OPTIONS: "-Xmx512m "
      SERVICE_PRECONDITION: "partnermanagement-postgres:5432"
    volumes:
      - ./conf/service/application.properties:/deployments/config/application.properties
    ports:
      - "9002:8080"

  partnermanagement-ui:
    image: ${DOCKER_IMAGE_REGISTRY_IP:-10.113.56.67}/ngp-${PROJECT:-develop}/partnermanagement-ui:${TAG}
    container_name: partnermanagement-ui
    restart: always
    networks:
      - ${partnermanagement_net:-partnermanagement_net}
    environment:
      SERVICE_PRECONDITION: "partnermanagement-service:8080"
    volumes:
      - ./conf/ui/api.config.json:/usr/share/nginx/html/assets/conf/api.config.json
    ports:
      - "9003:80"

volumes:
  partnermanagement-pgsql:
